# Generated by Django 4.1.3 on 2022-12-11 15:12

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('authorId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('price', models.BigIntegerField(blank=True, default=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('publisherId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
